### ISSUE TITLE
internal logic has failed

### ISSUE THREAD

**Issue by Jay24004** [Skelmis/Discord-Anti-Spam#100]
Traceback:
![image](https://user-images.githubusercontent.com/79038529/162795833-cfa1277c-2f1f-4f89-8cb9-0bb7d000e0eb.png)

Code: 
https://sourceb.in/719oWwKXch

**Comment by Skelmis** [comment]
What message triggered this?

**Comment by Jay24004** [comment]
> What message triggered this?

Message content was simple Hello

**Comment by Skelmis** [comment]
Okay. Could I get the package version and discord.py version please?

**Comment by Jay24004** [comment]
Discord-Anti-Spam: 1.3.0

DPY Version: `git+https://github.com/Rapptz/discord.py@629f36e7d78f034580572dc93659cae9082b48fe`
