### ISSUE TITLE
can´t import antispam

### ISSUE THREAD

**Issue by AMPW-german** [Skelmis/Discord-Anti-Spam#85]
Hi, as the title says, I can´t import antispam because "Import "antispam" could not be resolved". I´m using pycord and I just installed this module.
Edit: I tested it with installing discord.py but I cant import antispam. I just installed it through "pip install Discord-Anti-Spam".

**Comment by Skelmis** [comment]
Can you provide the following info and I'll try to reproduce.
Pycord version,
Antispam version
And some minimum reproduceable code

**Comment by AMPW-german** [comment]
pycord version doesn't really matter because I cant import antispam with discord.py, official pycord release and development version of pycord but I´m normally use the development version (pip install -U git+https://github.com/Pycord-Development/pycord)
Antispam version: 1.1.3 I think
I ´m using the basic bot example

**Comment by AMPW-german** [comment]
I tried to run the code and I got this error code after spamming some messages:
Ignoring exception in on_message
Traceback (most recent call 
last):
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\AMPW\Desktop\Discord Bot\MPB\test.py", line 17, in on_message     
    await bot.handler.propagate(message)
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\anti_spam_handler.py", 
line 66, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\anti_spam_handler.py", 
line 258, in propagate      
    main_return = await self.core.propagate(message, guild=guild)
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\core.py", line 55, in propagate
    guild_r = await self.propagate_user(message, guild) 
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\core.py", line 162, in 
propagate_user
    member_message = await self.handler.lib_handler.transform_message(
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\libs\dpy.py", line 195, in transform_message       
    return await self.substitute_args(item, message, warn_count, kick_count)        
  File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\libs\dpy.py", line 71, in substitute_args
    member_avatar = original_message.author.avatar.url
AttributeError: 'NoneType' object has no attribute 'url'

**Comment by AMPW-german** [comment]
Idk why but now I can import antispam

**Comment by AMPW-german** [comment]
but now if I try to use the same edited code in another file I get this error:
cannot import name 'AntiSpamHandler' from partially initialized module 'antispam' (most likely due to a circular import) (c:\Users\AMPW\Desktop\Discord Bot\MPB\antispam.py)
  File "C:\Users\AMPW\Desktop\Discord Bot\MPB\antispam.py", line 3, in <module>
    from antispam import AntiSpamHandler, Options
  File "C:\Users\AMPW\Desktop\Discord Bot\MPB\antispam.py", line 3, in <module>
    from antispam import AntiSpamHandler, Options

**Comment by Skelmis** [comment]
> pycord version doesn't really matter because I cant import antispam with discord.py, official pycord release and development version of pycord but I´m normally use the development version (pip install -U git+https://github.com/Pycord-Development/pycord) Antispam version: 1.1.3 I think I ´m using the basic bot example

I am unable to produce this. If you run into the issue jump in discord where I can help easier.



> I tried to run the code and I got this error code after spamming some messages: Ignoring exception in on_message Traceback (most recent call last): File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 352, in _run_event await coro(*args, **kwargs) File "c:\Users\AMPW\Desktop\Discord Bot\MPB\test.py", line 17, in on_message await bot.handler.propagate(message) File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\anti_spam_handler.py", line 66, in wrapper return await func(*args, **kwargs) File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\anti_spam_handler.py", line 258, in propagate main_return = await self.core.propagate(message, guild=guild) File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\core.py", line 55, in propagate guild_r = await self.propagate_user(message, guild) File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\core.py", line 162, in propagate_user member_message = await self.handler.lib_handler.transform_message( File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\libs\dpy.py", line 195, in transform_message return await self.substitute_args(item, message, warn_count, kick_count) File "C:\Users\AMPW\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\libs\dpy.py", line 71, in substitute_args member_avatar = original_message.author.avatar.url AttributeError: 'NoneType' object has no attribute 'url'

If I had to guess this is intents related.



> but now if I try to use the same edited code in another file I get this error: cannot import name 'AntiSpamHandler' from partially initialized module 'antispam' (most likely due to a circular import) (c:\Users\AMPW\Desktop\Discord Bot\MPB\antispam.py) File "C:\Users\AMPW\Desktop\Discord Bot\MPB\antispam.py", line 3, in from antispam import AntiSpamHandler, Options File "C:\Users\AMPW\Desktop\Discord Bot\MPB\antispam.py", line 3, in from antispam import AntiSpamHandler, Options

You name your file ``antispam``, and then go ``from antispam ...``. Its trying to import itself, name it something different

**Comment by Skelmis** [comment]
Looks to be resolved to me. Feel free to open again if not
