### ISSUE TITLE
import bug

### ISSUE THREAD

**Issue by NotASkidder** [Skelmis/Discord-Anti-Spam#96]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from antispam import AntiSpamHandler
ImportError: cannot import name 'AntiSpamHandler' from 'antispam' (/home/runner/SwelteringIncomparableUpgrades/venv/lib/python3.8/site-packages/antispam/__init__.py)

im doing this with replit and the pkg of antispam is 0.10 and of discord-anti-spam is 1.2.11

**Comment by Skelmis** [comment]
This is not an issue with my code, it's an issue with your requirements. Installing `antispam` overwrites my software, so uninstall it and only use `discord-anti-spam`

**Comment by Skelmis** [comment]
Feel free to re-open this if that doesn't fix your issue.
